---
title: "Chapter9 - Arranging plots"
output: html_notebook
---

# 9.1 Laying out plots side by side
```{r}
p1 <- ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy))

p2 <- ggplot(mpg) + 
  geom_bar(aes(x = as.character(year), fill = drv), position = "dodge") + 
  labs(x = "year")

p3 <- ggplot(mpg) + 
  geom_density(aes(x = hwy, fill = drv), colour = NA) + 
  facet_grid(rows = vars(drv))

p4 <- ggplot(mpg) + 
  stat_summary(aes(x = drv, y = hwy, fill = drv), geom = "col", fun.data = mean_se) +
  stat_summary(aes(x = drv, y = hwy), geom = "errorbar", fun.data = mean_se, width = 0.5)
```


```{r}
library(patchwork)

p1 + p2
```

```{r}
p1 + p2 + p3 + p4
```

## 9.1.1 Taking control of the layout

```{r}
p1 + p2 + p3 + plot_layout(ncol = 2)
```

```{r}
p1 / p2
```

```{r}
# Basically the same as using `+` but the intend is clearer
p3 | p4
```


```{r}
p3 | (p2 / (p1 | p4))
```


```{r}
layout <- "
AAB
C#B
CDD
"

p1 + p2 + p3 + p4 + plot_layout(design = layout)
```



```{r}
p1 + p2 + p3 + plot_layout(ncol = 2, guides = "collect")
```

```{r}
p1 + p2 + p3 + guide_area() + plot_layout(ncol = 2, guides = "collect")
```


## 9.1.2 Modifying subplots
```{r}
p12 <- p1 + p2
p12[[2]] <- p12[[2]] + theme_light()
p12
```


it is necessary to modify all subplots at once to e.g. give them a common theme. patchwork provides the `&` for this scenario:
```{r}
p1 + p4 & theme_minimal()
```

```{r}
p1 + p4 & scale_y_continuous(limits = c(0, 45))
```


## 9.1.3 Adding annotation

```{r}
p34 <- p3 + p4 + plot_annotation(
  title = "A closer look at the effect of drive train in cars",
  caption = "Source: mpg dataset in ggplot2"
)
p34
```


```{r}
p34 + plot_annotation(theme = theme_gray(base_family = "mono"))
```

```{r}
p34 & theme_gray(base_family = "mono")
```

```{r}
p123 <- p1 | (p2 / p3)
p123 + plot_annotation(tag_levels = "I") # Uppercase roman numerics
```

```{r}
p123[[2]] <- p123[[2]] + plot_layout(tag_level = "new")
p123 + plot_annotation(tag_levels = c("I", "a"))
```

# 9.2 Arranging plots on top of each other

```{r}
p1 + inset_element(p2, left = 0.5, bottom = 0.4, right = 0.9, top = 0.95)
```

```{r}
p1 + 
  inset_element(
    p2, 
    left = 0.4, 
    bottom = 0.4, 
    right = unit(1, "npc") - unit(15, "mm"), 
    top = unit(1, "npc") - unit(15, "mm"),
    align_to = "full"
  )
```

```{r}
p24 <- p2 / p4 + plot_layout(guides = "collect")
p1 + inset_element(p24, left = 0.5, bottom = 0.05, right = 0.95, top = 0.9)
```

```{r}
p12 <- p1 + inset_element(p2, left = 0.5, bottom = 0.5, right = 0.9, top = 0.95)
p12 & theme_bw()
```

```{r}
p12 + plot_annotation(tag_levels = 'A')
```

