---
title: "Chapter4 - Efficient workflow"
output: html_notebook
---

```{r}
library("DiagrammeR")
```

# 4.3 Project planning and management

## 4.3.3 Visualising plans with R

```{r}
# 
# check   http://mermaid-js.github.io/mermaid/#/gantt   for more

library("DiagrammeR")
# Define the Gantt chart and plot the result (not shown)
mermaid("gantt
        Section Initiation
        Planning           :a1, 2016-01-01, 10d
        Data processing    :after a1  , 30d")
```

# 4.4 Package selection


```{r}
# Function to convert degrees to radians
deg2rad <- function(deg) deg * pi / 180

# Create origins and destinations
o <- c(lon = -1.55, lat = 53.80)
d <- c(lon = -1.61, lat = 54.98)

# Convert to radians
o_rad <- deg2rad(o)
d_rad <- deg2rad(d)

# Find difference in degrees
delta_lon <- (o_rad[1] - d_rad[1])
delta_lat <- (o_rad[2] - d_rad[2])

# Calculate distance with Haversine formula
a <- sin(delta_lat / 2)^2 + cos(o_rad[2]) * cos(d_rad[2]) * sin(delta_lon / 2)^2
c <- 2 * asin(min(1, sqrt(a)))
(d_hav1 <- 6371 * c) # multiply by Earth's diameter
```

```{r}
# Find great circle distance with geosphere
(d_hav2 <- geosphere::distHaversine(o, d))
```


## 4.4.1 Searching for R packages

```{r}
# Search CRAN for mentions of haversine
RSiteSearch("haversine")
```

```{r}
pkgsearch::pkg_search(query = "haversine")
```

