---
title: "Chapter15 - Scales and guides"
output: html_notebook
---


# 15.1 Scale specification

```{r}
ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(colour = class))

## ==

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(colour = class)) +
  scale_x_continuous() + 
  scale_y_continuous() + 
  scale_colour_discrete()
```


```{r}
ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(colour = class)) + 
  scale_x_continuous("A really awesome x axis label") +
  scale_y_continuous("An amazingly great y axis label")
```


```{r}
ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  scale_x_continuous("Label 1") +
  scale_x_continuous("Label 2")

ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  scale_x_continuous("Label 2")
```


```{r}
ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(colour = class)) +
  scale_x_sqrt() + 
  scale_colour_brewer()
```

## 15.1.1 Exercises

### question 1

```{r}
ggplot(mpg, aes(displ)) + 
  scale_y_continuous("Highway mpg") + 
  scale_x_continuous() +
  geom_point(aes(y = hwy))

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  ylab("Highway mpg")


ggplot(mpg, aes(y = displ, x = class)) + 
  scale_y_continuous("Displacement (l)") + 
  scale_x_discrete("Car type") +
  scale_x_discrete("Type of car") + 
  scale_colour_discrete() + 
  geom_point(aes(colour = drv)) + 
  scale_colour_discrete("Drive\ntrain")

ggplot(mpg, aes(class, displ, colour = drv)) +
  geom_point() + 
  labs(x = "Type of car", y = "Displacement (l)", colour = "Drive\ntrain")

```

### question 2

```{r}
ggplot(mpg, aes(class, drv)) +
geom_point() +
scale_x_continuous() +
scale_y_continuous()
```

```{r}
ggplot(mpg, aes(displ, hwy)) +
geom_point() +
scale_x_discrete() +
scale_y_discrete()
```

# 15.2 Scale transformation

```{r}
# convert from fuel economy to fuel consumption
ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  scale_y_continuous(trans = "reciprocal")

# log transform x and y axes
ggplot(diamonds, aes(price, carat)) + 
  geom_bin2d() + 
  scale_x_continuous(trans = "log10") +
  scale_y_continuous(trans = "log10")
```

```{r}
ggplot(mpg, aes(displ, hwy)) + 
  geom_point() +
  scale_y_reverse()

ggplot(diamonds, aes(price, carat)) + 
  geom_bin2d() + 
  scale_x_log10() +
  scale_y_log10()
```

```{r}
# manual transformation
ggplot(mpg, aes(log10(displ), hwy)) + 
  geom_point()

# transform using scales
ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  scale_x_log10()
```

Regardless of which method you use, the transformation occurs before any statistical summaries. To transform after statistical computation use `coord_trans()`.


```{r}
base <- ggplot(faithfuld, aes(waiting, eruptions)) + 
  geom_raster(aes(fill = density)) + 
  scale_x_continuous(NULL, NULL, expand = c(0, 0)) +
  scale_y_continuous(NULL, NULL, expand = c(0, 0))
  
base
base + scale_fill_continuous(trans = "sqrt")
```

```{r}
df <- data.frame(x = runif(20), y = runif(20), z = sample(20))
base <- ggplot(df, aes(x, y, size = z)) + geom_point()

base 
base + scale_size(trans = "reverse")
```

# 15.4 Scale breaks


```{r}
toy <- data.frame(
  const = 1, 
  up = 1:4,
  txt = letters[1:4], 
  big = (1:4)*1000,
  log = c(2, 5, 10, 2000)
)
toy
axs <- ggplot(toy, aes(big, const)) + 
  geom_point() + 
  labs(x = NULL, y = NULL)

axs
axs + scale_x_continuous(breaks = c(2000, 4000))
```


```{r}
leg <- ggplot(toy, aes(up, up, fill = big)) + 
  geom_tile() + 
  labs(x = NULL, y = NULL) 

leg 
leg + scale_fill_continuous(breaks = c(2000, 4000))
```

```{r}
base <- ggplot(mpg, aes(displ, hwy, colour = cyl)) + geom_point()

base 
base + scale_colour_continuous(guide = guide_coloursteps())
base + guides(colour = guide_coloursteps())
```

# 15.5 Legend merging and splitting

## 15.5.1 Merging legends

```{r}
ggplot(toy, aes(up, up)) + 
  geom_point(size = 4, colour = "grey20") +
  geom_point(aes(colour = txt), size = 2) 

ggplot(toy, aes(up, up)) + 
  geom_point(size = 4, colour = "grey20", show.legend = TRUE) +
  geom_point(aes(colour = txt), size = 2) 
```

```{r}
base <- ggplot(toy, aes(const, up)) +
  scale_x_continuous(NULL, breaks = NULL)
base + geom_point(aes(colour = txt))
base + geom_point(aes(shape = txt))
base + geom_point(aes(shape = txt, colour = txt))
```

```{r}
base <- ggplot(toy, aes(const, up)) + 
  geom_point(aes(shape = txt, colour = txt)) + 
  scale_x_continuous(NULL, breaks = NULL)

base
base + labs(shape = "Split legend")
base + labs(shape = "Merged legend", colour = "Merged legend")
```

## 15.5.2 Splitting legends


```{r}
base <- ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(colour = factor(year)), size = 5) + 
  scale_colour_brewer("year", type = "qual", palette = 5) 

base
base + 
  ggnewscale::new_scale_colour() + 
  geom_point(aes(colour = cyl == 4), size = 1, fill = NA) + 
  scale_colour_manual("4 cylinder", values = c("grey60", "black"))
```

